### ISSUE TITLE
Orz, So how can I use this...?

### ISSUE THREAD

**Issue by sjx95** [momocow/HanaYome#1]
FKG player, too. I think I need a browser like this.
Sorry that I don't know Node.js at all, but how can I start this browser? 
Could you please give some simple instruction on README.md? 
Thanks.

**Comment by momocow** [comment]
Sure, I'll update it tomorrow maybe.
It's quite simple to start the browser, just go to [release](https://github.com/momocow/HanaYome/releases) and you'll find a link saying 'download executables', which will bring you to Google drive. Download one of the zip files according to your OS and unzip it. Finally you'll see 'hanayome.exe' in the unzipped folder.  

Noted that it's currently WIP so there are not many functions.  
What it can do now is simply 
- connecting to the game for you 
- resizing the flash area to fit the window
- reloading
- muting
- taking a screenshot into the clipboard

I'll keep working on it (I'm using my own browser too). It would be my pleasure to earn your feedback if you decide to play with this browser.

Or [Flower Master](https://github.com/lprensoft/FlowerMaster) is another good choice for you, which is a more functional one.

**Comment by sjx95** [comment]
OMG your download executables link is above the bold big "Download" so that I miss it...

Sorry for so stupid problem. I'll try this later.

Maybe you could upload the binary files on GitHub? Or give the link in readme?

**Comment by sjx95** [comment]
I searched "flower knight" instead of "美少女花骑士", so missed flower master. Flower master is written by C#, but I usually use Linux...

**Comment by momocow** [comment]
The binary is about 150MB (thanks for electron which includes a whole Chromium) so I'll put the link into README.
Must to say that execution under Linux is not testing yet so you are the **ALPHA** tester. That is, stability is not guarantee ;)

Always create a new issue if you find something buggy. I am glad to hear that.
